import React from "react";
import { ActivityIndicator, StyleSheet, Text, View, Image, TextInput, Button, TouchableOpacity, AsyncStorage, Modal } from "react-native";
import { connect } from 'react-redux'
import { Icon } from 'react-native-elements'
import { AnimatedCircularProgress } from 'react-native-circular-progress';
import AwesomeAlert from 'react-native-awesome-alerts';
import { getSuggestion } from "../../actions/quisionerAction";
import icon from 'react-native-vector-icons/Ionicons';
import PushNotification from 'react-native-push-notification';

class Suggestion extends React.Component {
  static navigationOptions = {
    tabBarLabel: 'Suggestion',
    // Note: By default the icon is only shown on iOS. Search the showIcon option below.
    tabBarIcon: ({ tintColor }) => (
      <Icon
        name='data-usage'
        color='#06a887' />
    ),
  }

  constructor() {
    super()
    this.state = {
      persen: 100,
      air: 0,
      konstanta: 0,
      showAlert: false,
      modalVisible: true,
      goalStatus: false
    }
  }

  componentDidMount() {
    AsyncStorage.getItem('drimerToken').then((value) => {
      this.props.getSuggestion(value)
    })
    .catch((err) => {
      console.log(err)
    })

      PushNotification.configure({
        onNotification: function(notification) {
          console.log( 'NOTIFICATION:', notification );
        },
        popInitialNotification: true,
        requestPermissions: true,
      })

    PushNotification.localNotification({

      id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
      ticker: "My Notification Ticker", // (optional)
      autoCancel: true, // (optional) default: true
      largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
      smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
      bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
      subText: "This is a subText", // (optional) default: none
      color: "red", // (optional) default: system default
      vibrate: true, // (optional) default: true
      vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
      tag: 'some_tag', // (optional) add tag to message
      group: "group", // (optional) add group to message
      ongoing: false, // (optional) set whether this is an "ongoing" notification

      /* iOS and Android properties */
      title: "DriMer Notification", // (optional, for iOS this is only used in apple watch, the title will be the app name onother iOS devices)
      playSound: true, // (optional) default: true
      soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the defaultsound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound'audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
      number: '10', // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
      actions: '["Yes", "No"]',  // (Android only) See the doc for notification actions to know more
    });

    PushNotification.localNotificationSchedule({
      message: `Minum yok guys, sisa 2 Liter lagi nih`, // (required)
      date: new Date(Date.now() + (60 * 1000)) // in 60 secs
    })
  }

  componentWillReceiveProps(nextProps) {
    AsyncStorage.getItem('air').then((value) => {
      if (value) {
        this.setState({
          air: value,
          konstanta: nextProps.waterNeed.toFixed(2)
        })
      } else {
        this.setState({
          air: nextProps.waterNeed.toFixed(2),
          konstanta: nextProps.waterNeed.toFixed(2)
        })
      }
    })

    AsyncStorage.getItem('persen').then((value) => {
      if (value) {
        this.setState({
          persen: Number(value),
        })
      }
    })

    if(nextProps.waterNeed) {
      this.setState({
        modalVisible: false
      })
    }
  }

  showAlert = () => {
    this.setState({
      showAlert: true
    });
  };

  hideAlert = () => {
    this.setState({
      showAlert: false
    });
  };

  minum(jumlahminum) {
    if(this.state.air <= 0) {
      var persen = this.state.persen
      var air = this.state.air

      var kurang = (jumlahminum / this.state.konstanta) * 100

      air = (air - jumlahminum).toFixed(2)
      persen = persen - kurang

      AsyncStorage.setItem('air', air).then(() => {
        console.log('yeah')
      }).catch((err) => {
        console.log(err)
      })

      AsyncStorage.setItem('persen', persen.toString()).then(() => {
        console.log('yeah')
      }).catch((err) => {
        console.log(err)
      })

      this.setState({
        air: air,
        persen: persen,
        goalStatus: true
      })         
    }

    else if (this.state.air - jumlahminum >= 0) {
      var persen = this.state.persen
      var air = this.state.air

      var kurang = (jumlahminum / this.state.konstanta) * 100

      air = (air - jumlahminum).toFixed(2)
      persen = persen - kurang

      AsyncStorage.setItem('air', air).then(() => {
        console.log('yeah')
      }).catch((err) => {
        console.log(err)
      })

      AsyncStorage.setItem('persen', persen.toString()).then(() => {
        console.log('yeah')
      }).catch((err) => {
        console.log(err)
      })

      this.setState({
        air: air,
        persen: persen
      })
    } 
    
    else if(!this.state.air - jumlahminum < 0) {
      var persen = this.state.persen
      var air = this.state.air

      var kurang = (jumlahminum / this.state.konstanta) * 100

      air = (air - jumlahminum).toFixed(2)
      persen = persen - kurang

      AsyncStorage.setItem('air', air).then(() => {
        console.log('yeah')
      }).catch((err) => {
        console.log(err)
      })

      AsyncStorage.setItem('persen', persen.toString()).then(() => {
        console.log('yeah')
      }).catch((err) => {
        console.log(err)
      })

      this.setState({
        air: air,
        persen: persen,
        showAlert: true,
        goalStatus: true
      })
    }
  }

  render() {
    return (
      <View>
        <Modal
         visible={this.state.modalVisible}
         animationType={'fade'}
         onRequestClose={() => this.closeModal()}
        >
          <View style={styles.modalContainer}>
            <View style={styles.innerContainer}>
              <Text style={styles.modalText}>Please wait</Text>
              <ActivityIndicator size="large" color="#06a887" />
            </View>
          </View>
        </Modal>
        <View style={styles.container}>
          <Text style={styles.textRec}>Today's Drink Target</Text>
          <AnimatedCircularProgress
            style={{
              marginTop: 20
            }}
            size={180}
            width={8}
            fill={this.state.persen}
            tintColor="#00e0ff"
            backgroundColor="white">
            {
              (fill) => (
                <View>
                  <Text style={styles.numberLiter}>
                    { this.state.air < 0? "+" + this.state.air * -1: this.state.air }
                  </Text>
                  <Text style={styles.points}>
                    Liter / day
                  </Text>
                </View>
              )
            }
          </AnimatedCircularProgress>
          <Text style={styles.textRec}>Tap your drink</Text>
          <View style={{width: 300, height: 150, flexDirection: 'row', alignItems: 'center' ,justifyContent: 'space-around'}}>
          <TouchableOpacity style={styles.ButtonStyle} onPress={() => { this.minum(0.6) }}>
            <Icon
            name='md-battery-full'
            type='ionicon'
            color='white'
            />
            <Text style={{color: 'white'}}>600 ml</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.ButtonStyle} onPress={() => { this.minum(0.24) }}>
            <Icon
            name='cup'
            type='material-community'
            color='white'
            />
            <Text style={{color: 'white'}}>240 ml</Text>
          </TouchableOpacity>
          </View>
        </View>

        <AwesomeAlert
          show={this.state.showAlert}
          showProgress={false}
          title="Congratulation"
          message="You have completed your liquid needs"
          closeOnTouchOutside={true}
          closeOnHardwareBackPress={false}
          showConfirmButton={true}
          confirmText="OK"
          confirmButtonColor="#DD6B55"
          onCancelPressed={() => {
            this.hideAlert();
          }}
          onConfirmPressed={() => {
            this.hideAlert();
          }}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    backgroundColor: '#296666',
    height: 550
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },

  numberLiter: {
    fontSize: 40,
    color: 'white',
    textAlign: 'center'
  },

  points: {
    fontSize: 28,
    color: 'white',
    textAlign: 'center'
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'white',
  },
  innerContainer: {
    alignItems: 'center',
  },
  modalText: {
    color: '#06a887',
    marginBottom: 30
  },

  ButtonStyle: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#06a887',
    width: 120,
    height: 120,
    borderRadius: 60,
    marginTop: 20
  },

  textRec: {
    fontSize: 18,
    color: "white",
    marginTop: 40

  }
});

const mapStateToProps = (state) => {
  // console.log('ini map', state)
  return {
    waterNeed: state.quisionerReducer.waterNeeds
  }
}

const mapActionToProps = (dispatch) => {
  return {
    getSuggestion: (token) => dispatch(getSuggestion(token))
  }
}

export default connect(mapStateToProps, mapActionToProps)(Suggestion)
